### ISSUE TITLE
Japanese characters not shown correctly

### ISSUE THREAD

**Issue by coolvitto** [diffractor/diffractor#168] opened 2024-05-13 16:30 UTC
Japanese file names cannot be displayed correctly.
![sshot-4](https://github.com/diffractor/diffractor/assets/160416811/fb0744f1-e34d-46ae-a9d8-e2c1f6816f81)

**Comment by ZacWalk** [comment] 2024-05-13 20:20
Looks like a bug. Could you send me that file for testing?

**Comment by coolvitto** [comment] 2024-05-13 23:40
ok,this one
![ダウンロード (11)](https://github.com/diffractor/diffractor/assets/160416811/9bf7a338-6433-4cfb-9a4b-a2a301cc4b23)

**Comment by ZacWalk** [comment] 2024-05-14 06:31
Thanks. What a great photo! I have been able to reproduce the problem. I wont have time to investigate this week but will keep you posted if I can find out the problem.

**Comment by ZacWalk** [comment] 2024-05-14 20:19
Maybe I have a fix for this. When you have time can you download and install from here:
https://diffractor.com/diffractor-setup.exe
This version has a small fix to hopefully improve drawing of text.

**Comment by coolvitto** [comment] 2024-05-15 01:12
Thank you for the update.
Thanks to you, Japanese can now be displayed correctly.
![sshot-3](https://github.com/diffractor/diffractor/assets/160416811/efed723b-6cfe-494f-8681-fdb2946502c8)

By the way, "ja.po" is not included in the installer yet, but will it be included in the next official release version?

I wish you all the best in your future development.

**Comment by ZacWalk** [comment] 2024-05-15 18:52
Installer was updated already. You should see an option to set Japanese language.
![image](https://github.com/diffractor/diffractor/assets/181544/13216800-63ba-4231-9268-1e9cf71dd6b6)

**Comment by coolvitto** [comment] 2024-05-15 23:35
The installer linked above does not install "ja.po".
![sshot-4](https://github.com/diffractor/diffractor/assets/160416811/72d196a5-9eea-400d-a2d9-56aa2f862593)

I have to copy it manually.

**Comment by ZacWalk** [comment] 2024-05-16 07:30
Oh - you are correct. My download server was caching an older version of the installer. I refreshed it. Can you try again from here:
https://diffractor.com/diffractor-setup.exe

**Comment by ZacWalk** [comment] 2024-05-16 18:40
Great news!
I will close this issue. Please open a new one if you have any more problems.

**Closed** 2024-05-16 19:02 UTC
