### ISSUE TITLE
GMT instead of local time

### ISSUE THREAD

**Issue by ZacWalk** [diffractor/diffractor#1] opened 2020-06-03 23:43 UTC
The time reported for movies (either .mp4 or .mov) copied from my iPhone 7 is off by +5 hours: a file that the Windows File Explorer properties reports as 28-May-2020 2:19 PM shows us as 28-May-2020 7:19 PM in Diffractor. 

My current time zone is GMT-5 -- is Diffractor giving me the time in GMT instead of local time?

**Comment by bjones1** [comment] 2020-06-09 02:39
@ZacWalk, thanks for taking a look. For fun, I changed my PC's time zone. Windows reports a different time/date for the movie, while Diffractor reports the same time/date. This suggests that the time/date is recorded in GMT on the .MOV file and that Diffractor needs to adjust this to local time. (The time/date reported by Windows is correct based on when the movie what shot.)

**Comment by bjones1** [comment] 2020-06-24 20:43
I just updated Diffractor to v122.7, and still see the same bug. I assume this will be in the next release?

**Comment by ZacWalk** [comment] 2020-07-18 23:20
@bjones1 there was work done on this for 122.8. After looking at what other applications do, the behaviour was changed to the following:

- Taken dates stored in EXIF metadata are interpreted as having no timezone information. Diffractor always shows them as stored. 
- The created date from the mvhd header in MOV files is interpreted to be in UTC and **displayed** in local time.

As far as I can tell, this should be the correct way to handle dates but I am interested if this works as expected?

**Comment by bjones1** [comment] 2020-07-19 03:29
@ZacWalk, thanks for working on this! I've downloaded 122.8 then tested it on an iPhone .mp4 file:
- Diffractor reports the date and time as 13-Jul-2020 at 11:13:23 AM.
- The Windows file explorer reports 13-Jul-2020 at 11:13:23 AM.
- The iPhone and iCloud report 13-Jul-2020 at 9:26:52 AM. This is when the movie was actually taken.
- Exiftool (https://exiftool.org/) reports the date/time original as 13-Jul-2020 9:26:52 AM, and the create date as 13-Jul-2020 at 16:13:23, or 11:13:23 AM in local time, since I'm in GMT-5.

So, the newer diffractor works better by presenting the local time, but appears to use the wrong EXIF tag (at least for iPhone movies.)

Doing some looking, https://discussions.apple.com/thread/7692554 claims that the later time is when the photos were uploaded to iCloud. Based on what I know, this is believable.

Full exiftool output:

```
C:\Users\bjones\Downloads\iCloud Photos>"..\exiftool(-k).exe" IMG_5480.MP4
ExifTool Version Number         : 12.01
File Name                       : IMG_5480.MP4
Directory                       : .
File Size                       : 14 MB
File Modification Date/Time     : 2020:07:18 21:52:05-05:00
File Access Date/Time           : 2020:07:18 22:02:08-05:00
File Creation Date/Time         : 2020:07:19 02:55:38-05:00
File Permissions                : rw-rw-rw-
File Type                       : MP4
File Type Extension             : mp4
MIME Type                       : video/mp4
Major Brand                     : MP4 v2 [ISO 14496-14]
Minor Version                   : 0.0.1
Compatible Brands               : isom, mp41, mp42
Movie Header Version            : 0
Create Date                     : 2020:07:13 16:13:23
Modify Date                     : 2020:07:13 16:13:29
Time Scale                      : 600
Duration                        : 0:00:33
Preferred Rate                  : 1
Preferred Volume                : 100.00%
Preview Time                    : 0 s
Preview Duration                : 0 s
Poster Time                     : 0 s
Selection Time                  : 0 s
Selection Duration              : 0 s
Current Time                    : 0 s
Next Track ID                   : 3
Track Header Version            : 0
Track Create Date               : 2020:07:13 16:13:23
Track Modify Date               : 2020:07:13 16:13:29
Track ID                        : 1
Track Duration                  : 0:00:33
Track Layer                     : 0
Track Volume                    : 100.00%
Balance                         : 0
Audio Format                    : mp4a
Audio Channels                  : 2
Audio Bits Per Sample           : 16
Audio Sample Rate               : 44100
Matrix Structure                : 1 0 0 0 1 0 0 0 1
Image Width                     : 1280
Image Height                    : 720
Media Header Version            : 0
Media Create Date               : 2020:07:13 16:13:23
Media Modify Date               : 2020:07:13 16:13:29
Media Time Scale                : 600
Media Duration                  : 0:00:33
Media Language Code             : und
Handler Type                    : Video Track
Handler Description             : Core Media Video
Graphics Mode                   : srcCopy
Op Color                        : 0 0 0
Compressor ID                   : avc1
Source Image Width              : 1280
Source Image Height             : 720
X Resolution                    : 72
Y Resolution                    : 72
Bit Depth                       : 24
Color Representation            : nclx 1 1 1
Video Frame Rate                : 30
Date/Time Original              : 2020:07:13 09:26:52-05:00
Media Data Size                 : 14757984
Media Data Offset               : 21202
Image Size                      : 1280x720
Megapixels                      : 0.922
Avg Bitrate                     : 3.55 Mbps
Rotation                        : 0
```

**Comment by ZacWalk** [comment] 2020-08-28 07:45
From the video file: There is another metadata field in a userdata/date block. That seems to be the date/time iCloud uses – “Date/Time Original” = “2020:08:10 08:00:39-05:00”. The userdata block seems to be unique to modern iPhones. I don’t see it in another video from android phones. I am not sure why the timestamps are 2 minutes different. Possibly related to when the file is actually constructed in the phone's storage.

**Comment by bjones1** [comment] 2020-08-31 15:25
Per another test, I've confirmed that the later time is indeed when the iPhone uploaded the photo to iCloud, while the earlier time is the actual time when the video was created. This was using an iPhone 7.

**Comment by ZacWalk** [comment] 2021-02-15 11:20
I believe fixed in current versions.

**Closed** 2021-02-15 11:20 UTC
Labels: bug
